scmAppsetRequeueAfterSeconds: 30
multiStageKargoAppSetHelmRepo: "https://github.com/kubriX-demo/kubriX-demo-oss"

destinationClusters:
  - name: in-cluster
    allowedTeams: [".*"]

teams: 
# new team stanza for team kubrix
  - name: kubrix
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/kubriX-stackit-demo/kubrix-apps
      path: demo-apps
      revision: main
    multiStageKargoAppSet:
      github:
        organization: kubriX-stackit-demo
